name: Docker Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Tag the Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/my-image-name:latest
        docker tag ghcr.io/${{ github.repository_owner }}/my-image-name:latest ghcr.io/${{ github.repository_owner }}/my-image-name:$(date +%Y%m%d%H%M%S)

    - name: Push Docker Images to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-image-name:latest
        docker push ghcr.io/${{ github.repository_owner }}/my-image-name:$(date +%Y%m%d%H%M%S)
